# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Publish Github Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get install -y pandoc
        python -m pip install --upgrade pip wheel
        python -m pip install -r requirements-ci.txt
        ipython kernel install --user --name=nicobako.github.io
    - name: Check code quality
      run: |
        black-nb --check blog/*.ipynb
    - name: Build blog
      run: |
        jupyter-book build blog
    - name: Deploy blog
      working-directory: blog/_build/html
      run: |
        touch .nojekyll
        git config --global user.email "nicobako@gmail.com"
        git config --global user.name "nicobako"
        git init
        git add .
        git commit -m "build html pages for gh-pages branch"
        git remote add origin https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY
        git push --force origin master:gh-pages
