# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Publish Github Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build and deploy docs
      run: |
        cd doc
        make html
        cd build/html
        touch .nojekyll
        git config --global user.email "${{GIT_CONFIG_EMAIL}}"
        git config --global user.name "${{GIT_CONFIG_NAME}}"
        git init
        git add .
        git commit -m "build html pages for gh-pages branch"
        git remote add origin https://github.com/nicobako/nicobako.github.io.git
        git push --force origin master:gh-pages
